config/routes.rb
Rails.application.routes.draw do
  
  get 'pizzasgit/status'

  devise_for :users
  
  resources :restaurants do
  	resources :pizzas
  end

  root 'restaurants#index'
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	belongs_to :user
	has_many :pizzas

	validates :name, presence: true, uniqueness: true
    validates :address, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
  has_many :pizzas       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@pizza = @restaurant.pizzas.create(params[:pizza].permit(:name, :price, :description))
		@pizza.user_id = current_user.id if current_user
		@pizza.save

		if @pizza.save
			redirect_to restaurant_path(@restaurant)
		else
			render 'new'
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:restaurant_id])
		@pizza = @restaurant.pizzas.find(params[:id])
	end	

	def update
		@restaurant = Restaurant.find(params[:restaurant_id])
		@pizza = @restaurant.pizzas.find(params[:id])

		if @pizza.update(params[:pizza].permit(:name, :price, :description))
			redirect_to restaurant_path(@restaurant)
		else
			render 'edit'
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
		@pizza = @restaurant.pizzas.find(params[:id])
		@pizza.destroy
		redirect_to restaurant_path(@restaurant)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		@restaurants = Restaurant.all.order("Created_at DESC")
	end

	def show
		@pizzas = @restaurant.pizzas
		
	end

	def new
		@restaurant = current_user.restaurants.build
	end

	def create
		@restaurant = current_user.restaurants.build(restaurant_params)
		
		if @restaurant.save
			redirect_to @restaurant
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @restaurant.update(restaurant_params)
			redirect_to @restaurant
		else
			render 'edit'
		end
	end

	def destroy
		@restaurant.destroy
		redirect_to root_path
	end

	private

	def find_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

	def restaurant_params
		params.require(:restaurant).permit(:name, :address, :open, :close)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.haml
%html
%head
	%title Arsen's rails forum
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags
%body
	%nav.navbar.navbar-inverse.navbar-fixed-top
		.navbar-header
			%button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
		#navbar.collapse.navbar-collapse
			%ul.nav.navbar-nav
				%li
					=link_to "PizzaNetwork", root_path
				- if user_signed_in?	 
					%li	
						=link_to "New Restaurant", new_restaurant_path
					%li
						=link_to "Log Out", destroy_user_session_path,:method => :delete	
				- else		
					%li
						=link_to "Sign Up", new_user_registration_path
					%li	
						=link_to "Sign In", new_user_session_path		

	- if notice
		#notice_wrapper
			%p.notice
				= notice
	- elsif alert
		#notice_wrapper
			%p.alert
				= alert	

= yield

app/views/pizzas/_form.html.haml
= simple_form_for([@restaurant, @restaurant.pizzas.build]) do |f|
	= f.input :name, label: "Dish name:"
	= f.input :price, label: "Price:"
	= f.input :description, label: "Ingredients:"
	= f.submit

app/views/pizzas/_pizza.html.haml
.wrap
	%h1= pizza.name
	%p= pizza.price
	%p= pizza.description

	= link_to "Edit", edit_restaurant_pizza_path(pizza.restaurant, pizza)
	= link_to "Delete", [pizza.restaurant, pizza], method: :delete, data: {confirm: "Are you sure?"}

app/views/pizzas/edit.html.haml
.wrap
	%h1 Edit pizza
	= simple_form_for([@restaurant, @pizza]) do |f|
		= f.input :name, label: "Dish name:"
		= f.input :price, label: "Price:"
		= f.input :description, label: "Ingredients:"
		= f.submit

app/views/restaurants/_form.html.haml
.wrap
	= simple_form_for @restaurant do |f|
		= f.input :name, label: "Restaurant name:"
		= f.input :address, label: "Restaurant address:"

		Work hours: 
		%br
		= f.time_select :open
		till
		= f.time_select :close
		%br
		= f.submit

app/views/restaurants/edit.html.haml
.wrap
	%h1 Edit restaurant data

	= render 'form'

	= link_to "Cancel", restaurant_path

app/views/restaurants/index.html.haml
.wrap
	- @restaurants.each do |restaurant| 
		%h2
			= link_to restaurant.name, restaurant
			

app/views/restaurants/new.html.haml
.wrap
	%h1 Add new restaurant network

	= render 'form'

app/views/restaurants/show.html.haml
.wrap
	%h1 
		Restaurant name: #{@restaurant.name}

	%h3 
		Restaurant address: #{@restaurant.address}

	%h3
		Work Hours: from
		= @restaurant.open.strftime("%H : %M")
		till	 
		= @restaurant.close.strftime("%H : %M")
	%br

	%h2
		= @restaurant.pizzas.count
		Dishes in the menu
	%h4	
		- @pizzas.each do |pizza|

			%h2
				Dish name: #{pizza.name} 
			%p 
				Dish price: #{pizza.price}
			%p 
				Ingredients: #{pizza.description}
			
			= link_to "Edit", edit_restaurant_pizza_path(pizza.restaurant, pizza)
			= link_to "Delete", [pizza.restaurant, pizza], method: :delete, data: {confirm: "Are you sure?"}

	%h3 Add another dish:
	= render "pizzas/form"


	=link_to "Edit", edit_restaurant_path(@restaurant), class: "button"
	=link_to "Destroy", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?"}, class: "button"
	=link_to "Home", root_path, class: "button"